# Generated by Django 5.0.2 on 2024-02-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objava',
            name='slika',
            field=models.ImageField(default='./backend/media/images/default.jpg', upload_to='images/'),
        ),
    ]
